name: Build and Deploy
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - uses: oven-sh/setup-bun@v2

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '1'
          persist-credentials: false
          submodules: 'recursive'

      - name: Checkout pointcloud_stitching Repository
        uses: actions/checkout@v4
        with:
          repository: iqr-lab/pointcloud_stitching
          path: pointcloud_stitching
          fetch-depth: '1'
          persist-credentials: false

      - name: Checkout iqr-vision Repository
        uses: actions/checkout@v4
        with:
          repository: iqr-lab/iqr-vision
          path: iqr-vision
          fetch-depth: '1'
          persist-credentials: false

      - name: Copy module docs
        run: |
          cp -rf pointcloud_stitching/README.md computer-vision/pointcloud-stitching.md
          cp -rf iqr-vision/README.md computer-vision/iqr-vision.md

      - name: Install Dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          branch: gh-pages
          folder: .vuepress/dist/
          clean: true