name: Build/Test/Deploy
on:
  push:
    branches-ignore:
      - gh-pages
  workflow_dispatch:
  pull_request:
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: oven-sh/setup-bun@v1
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '1'
          persist-credentials: false
          submodules: 'recursive'
      - name: Install
        run: bun install
      - name: Build
        run: bun run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          branch: gh-pages
          target-folder: .vuepress/dist/
          clean: true
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: oven-sh/setup-bun@v1
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '1'
          submodules: 'recursive'
      - name: Install
        run: bun install
      - name: Lint
        run: bun run lint-ci
  # spellcheck:
  #   name: Spellcheck
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/setup-node@v2-beta
  #       with:
  #         node-version: '16'
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: '0'
  #         submodules: 'recursive'
  #     - name: Install
  #       run: npm install
  #     - name: Spellcheck
  #       run: npm run spellcheck